name: enchanted_collection
description: A collection toolkit of useful data structures and algorithms for collections.
version: 1.1.1
repository: https://github.com/igormidev/enchanted_collection
issue_tracker: https://github.com/igormidev/enchanted_collection/issues

environment:
  sdk: ^3.2.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
